apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
  labels:
    name: transaction-deployment
    app: transaction
spec:
  replicas: 1
  selector:
    matchLabels:
      name: transaction-pod
      app: transaction
  template:
    metadata:
      name: transaction-pod
      labels:
        name: transaction-pod
        app: transaction
    spec:
      containers:
        - name: transaction-manager
          image: transaction-manager:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000