apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transaction-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /transaction-manager
            pathType: Prefix
            backend:
              service:
                name: transaction-service
                port:
                  number: 3000